// What each pane printed, kept on this machine so that quitting the app does
// not empty its scrollback.
//
// A PTY dies with the process that started it, and nothing here changes that: a
// restored pane is a new shell, and `session-restore.ts` still refuses to
// re-issue any command that does not resume something. What is kept is only the
// text the old pane had already printed — bytes, which do not need a process to
// stay true — so that the transcript of a long build or a failed migration is
// not the price of a restart.
//
// **It lives beside the workspace file, not inside it**, and that is the same
// decision `teammateCache.ts` made for the same reason, only more so. Scrollback
// is the largest and least valuable thing this app holds: a single pane's record
// can be as big as everything else in `workspace.json` put together, it is
// rewritten whenever a pane is finished with, and it is regenerated by the pane
// simply running again. `workspace.json` is the one file this app cannot afford
// to be unable to read — the store will refuse to write rather than overwrite an
// unreadable one — and megabytes of terminal output has no business sharing that
// risk, or that write path. So it is a directory of small files here: one pane
// per file, so a pane that is finished with is one `rm`, a file that will not
// parse costs that pane's record and no other, and writing one pane's transcript
// never rewrites another's.
//
// **Everything in it is bounded**, on disk as well as in memory, because a pane
// can print without limit and this is the one place that is written down. Each
// record is a capped tail; a file that has somehow grown past what this could
// have written is refused before its bytes are read; and a record is removed
// with the pane it belongs to, with a sweep at startup for the ones a crash
// orphaned. So the whole directory is the panes a person actually has open
// multiplied by one cap, and nothing else — one file per pane, whether that
// pane's record was written once or a thousand times.
//
// **It is written from three places**: a pane exiting, the app quitting, and a
// checkpoint taken while a pane is still running, which is what stops a machine
// losing power mid-build from taking the build's output with it.
// `scrollbackCheckpoints.ts` owns when the third one happens; what this file
// owns is that the three cannot get in each other's way. Writes are one chain
// rather than one per caller, so two of them never reach one path at the same
// moment; each write is a temp file and a rename, so a reader sees one whole
// version or the other and never half of either; and a write that would not
// change the file is skipped, so three callers saying the same thing is one
// write and the record's own timestamp stays honest about when its output was
// last new.

import { createHash } from 'node:crypto'
import { readFileSync, statSync } from 'node:fs'
import { readdir, rm } from 'node:fs/promises'
import { join } from 'node:path'
import { sanitizeRecordedOutput, tailFromLineBoundary, type RecordedScrollback } from '../terminals/scrollbackRecord'
import { writeJsonFileAtomically } from './atomicJsonFile'

/** Beside `workspace.json`, in the app's own data directory. */
export const SCROLLBACK_DIR_NAME = 'scrollback'
export const SCROLLBACK_RECORD_VERSION = 1

/**
 * How much of one pane's output is kept.
 *
 * The tail, never the head: a record is read by somebody coming back to what a
 * command ended up saying, and the beginning of a finished build is the part
 * nobody returns for — the same argument `EXITED_RETENTION_BYTES` makes about
 * memory, and this is half of that.
 *
 * 128 KiB is a few hundred to a couple of thousand dense lines, which is more
 * than a screen and enough to hold the end of a test run, a stack trace, or the
 * error a migration stopped on. It is also the number that has to be multiplied
 * by every pane a person keeps: thirty open panes is under 4 MB on disk, and the
 * same again in memory, since a restored record is held for as long as the pane
 * it belongs to is open. A megabyte a pane would buy a little more history for
 * ten times the cost of having any.
 */
export const MAX_RECORD_BYTES = 128 * 1024

/**
 * Read off the file before its bytes are, so a file that has somehow grown
 * cannot make this process allocate it just to find out it was too big.
 *
 * Well above what a capped record serialises to — JSON escaping can multiply a
 * pathological transcript several times over — and well below anything that
 * would be a problem to read.
 */
export const MAX_RECORD_FILE_BYTES = 1_000_000

/**
 * Which names this directory owns.
 *
 * A terminal id comes out of a file this app deliberately does not trust, so it
 * is checked before it is ever part of a path: `..` and a separator are the two
 * things that would make a record's file name reach somewhere that is not this
 * directory, and neither can survive this.
 */
const TERMINAL_ID = /^[A-Za-z0-9_-]{1,64}$/

/** Files this directory is allowed to contain, and therefore to remove. */
const OWN_FILE = /^[A-Za-z0-9_-]{1,64}\.json$|\.tmp$/

export type ScrollbackArchiveOptions = {
  /**
   * Said out loud rather than thrown. Nothing here is the user's own work — it
   * is a record the pane will make again — so a failure costs a transcript and
   * must never cost the pane, the window, or the launch.
   */
  onProblem?: (reason: string) => void
  now?: () => number
}

/**
 * The directory as the session manager holds it — `ScrollbackRepository` there
 * is the port this satisfies, and it is declared there rather than here so the
 * manager's three repositories are described in one place.
 *
 * `read` is synchronous because the restore that consumes it is: panes are
 * brought back before any window exists, in one pass, and a promise per pane
 * there would be a promise per pane in front of the first frame.
 */
export class ScrollbackArchive {
  readonly #onProblem: (reason: string) => void
  readonly #now: () => number

  #queue: Promise<void> = Promise.resolve()
  #reportedWriteFailure = false
  /**
   * What each pane's file was last asked to hold, as a digest.
   *
   * A record is written from three places now — a pane exiting, the app
   * quitting, and a checkpoint taken while a pane is still running — and they
   * overlap by design: a pane that exits and is then quit on has produced
   * nothing in between, and a full-screen program redrawing a spinner produces
   * bytes that the allowlist reduces to exactly what it reduced them to last
   * time. Every one of those would be a file rewritten to say what it already
   * says. Comparing the tail itself would mean holding a second copy of every
   * pane's record in memory, which is the one thing this module refuses to do,
   * so what is kept is a digest per open pane and nothing else.
   */
  readonly #lastWritten = new Map<string, string>()

  private constructor(
    readonly directory: string,
    options: ScrollbackArchiveOptions
  ) {
    this.#onProblem = options.onProblem ?? ((reason) => console.warn('[scrollback]', reason))
    this.#now = options.now ?? Date.now
  }

  /**
   * Opens the directory and sweeps it of records nothing points at any more.
   *
   * A record is pruned by `removeTerminal` the moment its pane is closed, the
   * way a mute and a standing permission are, so this sweep is not how pruning
   * normally happens. It is the backstop for the ways a record can be orphaned
   * without anybody closing a pane: a crash between the two writes, or a build
   * of this app that predates the directory. Without it those files would sit
   * here for the life of the installation.
   *
   * `keep` is undefined when the caller does not know which panes exist — a
   * workspace file that could not be read is the case, and the store refuses to
   * write over one of those precisely because the panes it describes are coming
   * back on some later launch. Not knowing is not the same as knowing there are
   * none, and sweeping on the second would throw away the transcripts of panes
   * that are about to return.
   */
  static async open(
    directory: string,
    keep: Iterable<string> | undefined,
    options: ScrollbackArchiveOptions = {}
  ): Promise<ScrollbackArchive> {
    const archive = new ScrollbackArchive(directory, options)
    if (keep === undefined) return archive
    const wanted = new Set([...keep].map((terminalId) => `${terminalId}.json`))

    let names: string[]
    try {
      names = await readdir(directory)
    } catch {
      // Nothing has been written yet, which is every first launch.
      return archive
    }

    for (const name of names) {
      if (wanted.has(name) || !OWN_FILE.test(name)) continue
      try {
        await rm(join(directory, name), { force: true })
      } catch (error) {
        archive.#onProblem(`could not remove ${name}: ${describe(error)}`)
      }
    }
    return archive
  }

  /**
   * The pane's record, or undefined when there is none to be had.
   *
   * Every ending is the same ending on purpose — no file, a file from a build
   * that wrote a different shape, a file somebody edited, a file too big to be
   * one of ours — because the caller can do exactly one thing about any of them:
   * open the pane with nothing above the prompt. A pane that fails to open
   * because its scrollback would not parse is a far worse outcome than a pane
   * that opens empty.
   */
  read(terminalId: string): RecordedScrollback | undefined {
    const path = this.#pathFor(terminalId)
    if (path === undefined) return undefined

    try {
      const stats = statSync(path)
      if (stats.size > MAX_RECORD_FILE_BYTES) {
        this.#onProblem(`${path} is ${stats.size} bytes, past the ${MAX_RECORD_FILE_BYTES} allowed`)
        return undefined
      }
      const raw: unknown = JSON.parse(readFileSync(path, 'utf8'))
      if (typeof raw !== 'object' || raw === null) return undefined
      const { text, recordedAt, endedAt } = raw as Record<string, unknown>
      if (typeof text !== 'string' || text.length === 0) return undefined
      // `endedAt` is what a build before checkpoints called this, and it is
      // still read here rather than versioned away: the two spell one number
      // the same way, the shape is otherwise unchanged, and an upgrade that
      // dated every restored pane to the moment of the upgrade would be a
      // worse answer than reading a field by its old name.
      const at = typeof recordedAt === 'number' ? recordedAt : endedAt

      // Sanitised and capped again here, not only on the way in: the file is the
      // boundary whatever wrote it, and the bytes it holds describe themselves
      // to a terminal rather than to this process.
      const kept = tailFromLineBoundary(sanitizeRecordedOutput(text), MAX_RECORD_BYTES)
      if (kept.length === 0) return undefined
      return { text: kept, recordedAt: typeof at === 'number' && Number.isFinite(at) ? at : this.#now() }
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        this.#onProblem(`could not read the record for ${terminalId}: ${describe(error)}`)
      }
      return undefined
    }
  }

  /**
   * Writes the capped, inert tail of `text`. Queued; `flush` waits for it.
   *
   * A write that would not change the file is not made at all, which is how
   * three callers writing the same record stay one file write. The timestamp is
   * part of what is skipped, deliberately: it says when the pane's output was
   * last written down, and rewriting it would move it forward without anything
   * having been printed.
   */
  put(terminalId: string, text: string): void {
    const path = this.#pathFor(terminalId)
    if (path === undefined) return

    const kept = tailFromLineBoundary(sanitizeRecordedOutput(text), MAX_RECORD_BYTES)
    if (kept.length === 0) {
      this.remove(terminalId)
      return
    }

    const fingerprint = createHash('sha256').update(kept).digest('base64')
    if (this.#lastWritten.get(terminalId) === fingerprint) return
    // Taken now rather than when the write lands, so that a second `put` of the
    // same text is skipped even while the first is still queued — which is
    // exactly the shape of an exit and a quit arriving together.
    this.#lastWritten.set(terminalId, fingerprint)

    const document = {
      version: SCROLLBACK_RECORD_VERSION,
      terminalId,
      recordedAt: this.#now(),
      text: kept
    }
    this.#enqueue(
      async () => {
        await writeJsonFileAtomically(path, document)
      },
      `could not write the record for ${terminalId}`,
      // A write that failed left something else on disk, so the pane must not
      // be remembered as holding this. Only if nothing newer has been promised
      // since: a later `put` that succeeds is the truth about the file.
      () => {
        if (this.#lastWritten.get(terminalId) === fingerprint) this.#lastWritten.delete(terminalId)
      }
    )
  }

  /** Drops a pane's record, because the pane itself has been dropped. */
  remove(terminalId: string): void {
    const path = this.#pathFor(terminalId)
    if (path === undefined) return
    this.#lastWritten.delete(terminalId)
    this.#enqueue(async () => {
      await rm(path, { force: true })
    }, `could not remove the record for ${terminalId}`)
  }

  /** Waits for everything queued. Called on the way out, so the last write lands. */
  async flush(): Promise<void> {
    let awaited: Promise<void>
    do {
      awaited = this.#queue
      await awaited
    } while (awaited !== this.#queue)
  }

  #pathFor(terminalId: string): string | undefined {
    if (!TERMINAL_ID.test(terminalId)) {
      this.#onProblem(`refusing a record for an id that is not one: ${JSON.stringify(terminalId)}`)
      return undefined
    }
    return join(this.directory, `${terminalId}.json`)
  }

  /**
   * One chain rather than one write per pane in parallel, so a shutdown writing
   * every pane at once cannot hold a hundred file handles open at the same
   * moment; each write is small and the whole queue is one directory's worth.
   */
  #enqueue(work: () => Promise<void>, failure: string, onFailure?: () => void): void {
    this.#queue = this.#queue.then(async () => {
      try {
        await work()
        this.#reportedWriteFailure = false
      } catch (error) {
        onFailure?.()
        // Said once. A full or read-only disk fails every pane on the way out,
        // and one line per pane would bury the reason in the repetition.
        if (this.#reportedWriteFailure) return
        this.#reportedWriteFailure = true
        this.#onProblem(`${failure}: ${describe(error)}`)
      }
    })
  }
}

function describe(error: unknown): string {
  return error instanceof Error ? error.message : String(error)
}
